### ISSUE TITLE
Maybe you want to add concrete theme previews ...

### ISSUE THREAD

**Issue by kirchsth** [mweagle/C4-PlantUML-Themes#1]
Hi @mweagle ,

thank you for your themes, your have a lot of useful color combinations.

With following code you could create a concrete preview for each theme

```
@startuml
!$useTheme = "puml-theme-cb_seq_OrRd_9.puml"
!$useTheme = "https://raw.githubusercontent.com/mweagle/C4-PlantUML-Themes/main/palettes/" +  $useTheme
!include $useTheme
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/percy/TestAllElementsWithLegend.puml
@enduml
```

And if you would use @ryardley [python script](https://gist.github.com/ryardley/64816f5097003a35f9726aab676920d0) and encode the  code to an image url you could create a preview image similar to my (which I did manually, and which is not stored as image).

## puml-theme-cb_seq_OrRd_9.puml

![](https://raw.githubusercontent.com/mweagle/C4-PlantUML-Themes/main/palettes/puml-theme-cb_seq_OrRd_9.png)

![](https://www.plantuml.com/plantuml/png/XOz1IyGm48Nl_HNPuatQkNXH45R4sueYAnvBcWnjO9ADcGcB_zv93o8Yx2cPUVFUnzkps28rKhUxgep75IEQUzDdNGtIfi7D4-Fdz5BU_7GxDg7_SxoAPBu3AFOyBa7MEgjQt2a99XdTAK8yerq8uV5cU2MRvFtvC6nsXcX3Wcm9HNJgpRKnF-7TBYH7rUD_gylKt52j28kdCF-cAvO52sHrVC4HMHw8daW1IVX3qmwuOF9RtMwlFts_0G00)

BR Helmut

**Comment by mweagle** [comment]
Thanks for the pointer - will make preview images.

**Comment by mweagle** [comment]
Uploaded preview images to the [README](https://github.com/mweagle/C4-PlantUML-Themes)

**Comment by kirchsth** [comment]
looks great, now it offers a very good overview
thank you
Helmut
