### ISSUE TITLE
Many themes have light gray/yellow (nearly invisible) arrows

### ISSUE THREAD

**Issue by kirchsth** [mweagle/C4-PlantUML-Themes#2]
I tried all your themes via the attached themes2.puml file (which I copied in my local C4-PlantUML/percy/Themes2.puml and opened in Visual Studio Code and checked in preview) and many of them have (at least for me) nearly invisible arrows.
E.g. in following sample there is a (very) light gray arrow between System and External System.

```plantuml
@startuml
!$useTheme = "puml-theme-cb_div_BrBG_11.puml"
!$useTheme = "https://raw.githubusercontent.com/mweagle/C4-PlantUML-Themes/main/palettes/" +  $useTheme
!include $useTheme
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/percy/TestAllElementsWithLegend.puml
@enduml
```

![](https://www.plantuml.com/plantuml/png/XOz1ImCn48Nl-olInPli3WLFWb0hugM2Xuh79PiCku596Z8JY__UIGyY8lIKpBnvx-FjM6oH6gdRt5J6uueHpOFfiwu6QTFWvic7psbVzY_JTZisfVzplOfalWSezZmkGTOwgrhSAGac6TqfGZoZNGZXwMvu8vla_VKmNEmCqOO4sHAAwDIRMsD-mhjDI8wgn_zMrwcveLeJ5azX_arNB0iMoEhuWYEoF18zamAIy8Uc7N31v2zrkvt-zFq6)

Additional I think your usage section/sample looks very complex for me, why is a normal `!theme` not enough?
Did I oversee something?

```plantuml
@startuml

!theme cb_seq_OrRd_9 from https://raw.githubusercontent.com/mweagle/C4-PlantUML-Themes/main/palettes

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Person(personAlias, "Label", "Optional Description")
Container(containerAlias, "Label", "Technology", "Optional Description")
System(systemAlias, "Label", "Optional Description")
Rel(personAlias, containerAlias, "Label", "Optional Technology")
@enduml
```

![](https://www.plantuml.com/plantuml/png/ZS_DJiCm30VmUvyYwwb8jBbmWTFGE0vj6kDSfQbf8paVsAwclJrf9GO8WNQo4ya__xrcCIIJns8b8tXGjciPtjiT7VhsNhrHz6eKIVoWDPbJCpWPfsvY81k3G936Hg_z2So0e3TtzHvDaDVdRNsSETRUkA2JGH01BegL2nQd7gv0KvRcP3LBZwxxZcUL1IX_jPiyaLS0DMc-OW_4CLHfAO_e3D-gSciwm38tkoGk1eFg2TYIMrxbJN4nAllP_HezWXr3n3YS_u5UpYpWArxAjTiFW3_pNaByBNoboS0QGfzl_m00)

Thank you and best regards
Helmut
[Themes2.zip](https://github.com/mweagle/C4-PlantUML-Themes/files/11301979/Themes2.zip)

**Comment by mweagle** [comment]
> Additional I think your usage section/sample looks very complex for me, why is a normal !theme not enough?

I prefer to be able to edit all the theme files locally with a local server render in VSCode. Adding the conditional enables me to edit locally and then push all the changes as a single working commit.

**Comment by mweagle** [comment]
> many of them have (at least for me) nearly invisible arrows

Thanks - the arrow and line colors are the mid-color index of the palette, which for some palettes is very light. I'll update to pick one of the colors at the end of the palette.

**Comment by mweagle** [comment]
Fixed arrow colors and updated boundary colors with [7bac2848af0d1748a042bb5fcab4f84bef2e5935](https://github.com/mweagle/C4-PlantUML-Themes/commit/7bac2848af0d1748a042bb5fcab4f84bef2e5935).
